import Product from "../models/Product";

const defaultProducts = [
  {
    productId: "1",
    name: "Classic Aviator",
    price: 199,
    originalPrice: 249,
    image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500&h=500&fit=crop",
    category: "Sunglasses",
    brand: "Ray-Ban",
    material: "Metal",
    color: "Gold",
    gender: "Unisex",
    lensType: "UV Protection",
    frameSize: "Large",
    rating: 4.8,
    reviews: 124,

  },
  {
    productId: "2",
    name: "Modern Round Frame",
    price: 179,
    image: "https://images.unsplash.com/photo-1559056199-641a0ac8b3f2?w=500&h=500&fit=crop",
    category: "Eyeglasses",
    brand: "Warby Parker",
    material: "Acetate",
    color: "Black",
    gender: "Unisex",
    lensType: "Blue Light Filter",
    frameSize: "Medium",
    rating: 4.6,
    reviews: 89,

  },
  {
    productId: "3",
    name: "Minimal Cat Eye",
    price: 149,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&h=500&fit=crop",
    category: "Sunglasses",
    brand: "Gucci",
    material: "Acetate",
    color: "Tortoise",
    gender: "Women",
    lensType: "Polarized",
    frameSize: "Small",
    rating: 4.7,
    reviews: 156,

  },
  {
    productId: "4",
    name: "Premium Blue Light",
    price: 159,
    image: "https://images.unsplash.com/photo-1508296695146-367ec3be0d35?w=500&h=500&fit=crop",
    category: "Computer Glasses",
    brand: "Warby Parker",
    material: "Metal",
    color: "Silver",
    gender: "Unisex",
    lensType: "Blue Light Filter",
    frameSize: "Large",
    rating: 4.5,
    reviews: 67,

  },
  {
    productId: "5",
    name: "Sports Performance",
    price: 249,
    originalPrice: 299,
    image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500&h=500&fit=crop",
    category: "Sports",
    brand: "Oakley",
    material: "Plastic",
    color: "Black",
    gender: "Unisex",
    lensType: "Polarized",
    frameSize: "Large",
    rating: 4.9,
    reviews: 201,

  },
  {
    productId: "6",
    name: "Elegant Rectangle",
    price: 189,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&h=500&fit=crop",
    category: "Eyeglasses",
    brand: "Prada",
    material: "Metal",
    color: "Rose Gold",
    gender: "Women",
    lensType: "UV Protection",
    frameSize: "Small",
    rating: 4.4,
    reviews: 45,

  },
  {
    productId: "7",
    name: "Vintage Wayfarer",
    price: 179,
    image: "https://images.unsplash.com/photo-1559056199-641a0ac8b3f2?w=500&h=500&fit=crop",
    category: "Sunglasses",
    brand: "Ray-Ban",
    material: "Acetate",
    color: "Brown",
    gender: "Men",
    lensType: "Polarized",
    frameSize: "Large",
    rating: 4.6,
    reviews: 98,

  },
  {
    productId: "8",
    name: "Minimalist Clear",
    price: 139,
    image: "https://images.unsplash.com/photo-1508296695146-367ec3be0d35?w=500&h=500&fit=crop",
    category: "Eyeglasses",
    brand: "Warby Parker",
    material: "Acetate",
    color: "Clear",
    gender: "Unisex",
    lensType: "Standard",
    frameSize: "Medium",
    rating: 4.3,
    reviews: 76,

  },
  {
    productId: "9",
    name: "Luxury Oversized",
    price: 299,
    image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500&h=500&fit=crop",
    category: "Sunglasses",
    brand: "Chanel",
    material: "Acetate",
    color: "Black",
    gender: "Women",
    lensType: "Polarized",
    frameSize: "Extra Large",
    rating: 4.8,
    reviews: 142,

  },
  {
    productId: "10",
    name: "Classic Round",
    price: 169,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&h=500&fit=crop",
    category: "Eyeglasses",
    brand: "Oakley",
    material: "Metal",
    color: "Gold",
    gender: "Unisex",
    lensType: "Blue Light Filter",
    frameSize: "Medium",
    rating: 4.5,
    reviews: 88,

  },
  {
    productId: "11",
    name: "Urban Streetwear",
    price: 159,
    image: "https://images.unsplash.com/photo-1559056199-641a0ac8b3f2?w=500&h=500&fit=crop",
    category: "Sunglasses",
    brand: "Warby Parker",
    material: "Acetate",
    color: "Tortoise",
    gender: "Men",
    lensType: "UV Protection",
    frameSize: "Medium",
    rating: 4.7,
    reviews: 112,

  },
  {
    productId: "12",
    name: "Premium Titanium",
    price: 279,
    image: "https://images.unsplash.com/photo-1508296695146-367ec3be0d35?w=500&h=500&fit=crop",
    category: "Eyeglasses",
    brand: "Gucci",
    material: "Titanium",
    color: "Silver",
    gender: "Unisex",
    lensType: "Standard",
    frameSize: "Medium",
    rating: 4.9,
    reviews: 167,

  },
];

export async function initializeProducts(): Promise<void> {
  await Promise.all(
    defaultProducts.map((product) =>
      Product.updateOne(
        { productId: product.productId },
        { $setOnInsert: product },
        { upsert: true }
      )
    )
  );
}
